version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns: ['xunit*', 'Microsoft.NET.Test.Sdk', 'FluentAssertions']
    ignore:
      - dependency-name: FluentAssertions
        versions: ['>=8']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
